# Generated by Django 5.1.4 on 2025-01-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_directorsmessage_delete_directormessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='focus_areas/')),
            ],
        ),
    ]
