# Generated by Django 5.1.4 on 2025-01-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_missionstatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='amount_raised',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
