# Generated by Django 5.1.4 on 2025-01-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_campaign_amount_raised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/'),
        ),
    ]
