# Generated by Django 5.1.4 on 2025-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_campaign_donations_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date',
            new_name='donation_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='donations_received',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(),
        ),
    ]
