# Generated by Django 5.1.4 on 2025-01-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_staticpagecontent_remove_event_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_sliders/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
