# Generated by Django 5.1.4 on 2025-01-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_heroslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='button_link',
            field=models.CharField(blank=True, help_text="Use relative URLs like '/donate' or absolute URLs like 'http://example.com'.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_sliders/'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
