# Generated by Django 5.1.4 on 2025-01-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(default='email', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(default='email', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
