# Generated by Django 5.1.4 on 2025-01-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='location', max_length=255),
            preserve_default=False,
        ),
    ]
