# Generated by Django 5.1.4 on 2025-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donor_name',
            new_name='payment_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donation_date',
        ),
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='order_id',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
